---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

jobs:

  test:
    name: Molecule
    runs-on: self-hosted
    strategy:
      matrix:
        distro:
          - centos8
          - centos7
          - debian10
          - debian9
          - ubuntu2204
          - ubuntu2004

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-docker yamllint ansible-lint docker netaddr dnspython

      - name: Install galaxy role
        run: |
          ansible-galaxy role install -f -r requirements.yml
          ansible-galaxy role remove udienz.bind

      - name: Run Molecule Primary/Secondary/Forwarder converge
        run: molecule converge
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Run Molecule Primary/Secondary/Forwarder destroy
        run: molecule destroy
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Run Molecule Shared Inventory tests
        run: molecule test --scenario-name shared_inventory
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
